### ISSUE TITLE
bug connexion et récompense

### ISSUE THREAD

**Issue by ImLacy** [MineWeb/Plugin-Vote#10]
Bonjour,
le bouton "Est-ce que le joueur doit être connecté sur le serveur ?" ne fonctionne pas 
je m'explique quand je coche ce bouton et que je vote ça donne quand même une récompense alors que toutes mes récompenses ont ce bouton coché
Pouvez-vous réglez ce problème ? 
Cordialement, Azhuk
PS: j'utilise Rcon  pour lier le serveur et le plugin mineweb

**Comment by Eywek** [comment]
Cette option n'est pas prise en compte en RCON.
