### ISSUE TITLE
erreur de maj via panel

### ISSUE THREAD

**Issue by sadoj-kuro** [MineWeb/Plugin-Vote#5]
Erreur : Le plugin ne peut pas être installé/mis à jour car le CMS ne dispose pas des droits d'écriture dans le dossier /app/Plugin/ (775 ou 755).

alors que le dossier a les perm et que pour le plugin forum sa a marcher

**Comment by Eywek** [comment]
Devrait être corrigé depuis https://github.com/MineWeb/MineWebCMS/releases/tag/v1.5.2
