### ISSUE TITLE
[Suggestion] Récompense pour plus tard désactivable

### ISSUE THREAD

**Issue by CyanurePV** [MineWeb/Plugin-Vote#63]
Bonjour,
J'ai beau fouiller sur MineWeb et sur les configuration du plugin vote, je ne trouve aucune option qui correspondrait à désactiver le fait de pouvoir récupérer ses récompenses plus tard de sorte à ce que le joueur soit obligé de récupérer sa récompenses instantanément.
Sauf erreur de ma part, je pense qu'une telle option serait un avantage.
Je possède la dernière MAJ (V2.7.3)

En attente de votre retour.
CyanurePV

**Comment by nivcoo** [comment]
https://pics.edensky.fr/2020-04/25/00-39_ZfJl.png c'est désactivable via les permissions ^^

**Comment by CyanurePV** [comment]
> https://pics.edensky.fr/2020-04/25/00-39_ZfJl.png c'est désactivable via les permissions ^^

ÉDIT : J’ai trouvé merci infiniment le plugin est génial 😌

Ha je n’ai pas trouvé cette case je vais fouiller plus profondément

**Comment by nivcoo** [comment]
C'est dans général -> permission ^^

**Comment by CyanurePV** [comment]
> C'est dans général -> permission ^^

En effet j’ai trouvé à l’instant ! 
Merci pour votre aide.
