### ISSUE TITLE
chargement infini vote

### ISSUE THREAD

**Issue by ImLacy** [MineWeb/Plugin-Vote#8]
Bonjour,
J'ai un problème avec le système de vote plus précisement sur le site serveurs-minecraft.com
La validation du vote charge indéfiniment sans avoir de erreur de les log de mineweb

Comment régler ce problème ?

**Comment by Eywek** [comment]
`Mais sinon c'est sûrement que tu as mal configuré le type du site de vote et donc le vote n'est jamais vérifié.`
